### ISSUE TITLE
Building static library.

### ISSUE THREAD

**Issue by Gert-Jan** [nokotan/VSExtForEmscripten#1]
I've been using VSExtForEmscripten for a bit, and it's pretty great to build wasm projects from Visual Studio.
However now I'm experimenting with building and linking static libraries, which is where I run into some issues. The problem is that the .a file cannot be linked. The following error is given:
`emcc : error : TestLibrary.a: Unknown format, not a static library!`

When I set the project Configuration Type to "Static LLVM Bitcode Library (.a)" it runs something like this when building: 
`emcc.bat Main.o -o TestLibrary.a`

While I would expect something more like this:
`emar.bat rcs TestLibrary.a Main.o`

**Comment by nokotan** [comment]
Thanks for reporting this issue.

I'm working on creating patch in `bugfix-broken-ar` branch, and releasing new version after checking that this patch should work.
You can also try developing version in [GitHub Actions Artifact](https://github.com/nokotan/VSExtForEmscripten/actions/runs/656496444).

**Comment by nokotan** [comment]
This unexpected behavior should be fixed in [v0.3.3](https://github.com/nokotan/VSExtForEmscripten/releases/tag/v0.3.3).
Please reopen this issue if you find something wrong related to this issue in this version.

**Comment by Gert-Jan** [comment]
Thanks for the quick fix! This works great!

One last recommendation. When I started to use this extension it took me a while to figure out that I could set the Emscripten Toolchain path in the project properties. It may be beneficial for future users to mention this in the readme.

**Comment by nokotan** [comment]
Thanks for your nice recommendation!

I added a brief explanation about first step to use this tool in [commit 37db9571](https://github.com/nokotan/VSExtForEmscripten/commit/37db95717a7231e6865a642ab741bc7dec16b3d0).
