### ISSUE TITLE
Additional Library Directories tab doesn't do anything

### ISSUE THREAD

**Issue by Sedomanai** [nokotan/VSExtForEmscripten#11]
I cannot add new library directories using Properties->Enscription Linker->General->Additional Library Directories. 
I tried using both relative and absolute paths, forward and backward slashes, none of them worked. 

And I have to specify the entire (relative) path instead of just library filename in the Linker->Input->Additional Dependencies tab.
(i.e. ../lib/test.a instead of test.a)

**Comment by nokotan** [comment]
Additional Library Directories should be inputted with Windows style paths. 
Filling the `Emscripten/C++ Directories > Library Directories` instead of `Additional Library Directories` also does nothing?

Or, maybe the version specific problem of Visual Studio.
