### ISSUE TITLE
Language version seems to have no effect

### ISSUE THREAD

**Issue by supsm** [nokotan/VSExtForEmscripten#14]
Setting the language version does not add the `-std` flag to clang or emcc, causing some of my files to not compile properly. It is temporarily fixed by adding `-std=c++20` to additional commandline arguments and removing all .c files

**Comment by nokotan** [comment]
Thank you for your investigation and your patience.

This problem will be fixed in v0.7.0, includes https://github.com/nokotan/VSExtForEmscripten/commit/8677c21369438efb2bc60bbb0b7ae0df900f2cd0.
