### ISSUE TITLE
No cpp file property pages after updating to 0.6.4

### ISSUE THREAD

**Issue by HolgerStrauss** [nokotan/VSExtForEmscripten#16]
Steps to reproduce (using VSExtForEmscripten 0.6.4, Visual Studio 2022 V17.2.3):

- Create a new "Plan Emscripten Project"
- In the Solution Explorer, right click on "Main.cpp" and select "Properties"
- A dialog appears saying "There are no property pages for the selection".

However, the property page for the project is still working. Can also be reproduced with an Emscripten project created with a previous version of VSExtForEmscripten.

I cross checked by manually by switching between VSExtForEmscripten 0.6.3 and 0.6.4: With 0.6.3 the property page is still working, with 0.6.4 it is unfortunately broken.

**Comment by nokotan** [comment]
Thank you for your investigation and your patience.

This problem will be fixed in v0.7.0, includes f462a98.
