### ISSUE TITLE
Dropping VS 2017 support

### ISSUE THREAD

**Issue by Reputeless** [nokotan/VSExtForEmscripten#18]
By dropping VS 2017 support, a set of the extension software can be consolidated into one.
- (internal) [discussion](https://scrapbox.io/mitouadv-siv3d/2022-07-13_%E3%82%B3%E3%82%A2%E3%82%BF%E3%82%A4%E3%83%A0#62ce53eb1fe6c30000581458)
- (internal) [report](https://siv3d.slack.com/archives/CS2EPGWAH/p1651933612286689)

**Comment by nokotan** [comment]
It may be good time to withdraw main stream support for Visual Studio 2017, as Microsoft does, and building extension with Visual Studio 2017 is not longer available on GitHub workflows.

Making a series of extensions separated can provide updates to any version of Visual Studio, also Visual Studio 2017 even if it lost main stream support. Is there some reason to merge extension into one?

**Comment by nokotan** [comment]
It seems that Emscripten.Build.Definition and Emscripten.Debugger can be safely merged, keeping it separated that WebAssembly debugger module and Visual Studio 2017 build target module.

I still have question to your motivation of consolidating extensions, but it's acceptable to me and possible to do.

**Comment by nokotan** [comment]
In next release, v0.7.0, package dependencies are updated as described previous comment, please refer [GitHub Releases](https://github.com/nokotan/VSExtForEmscripten/releases/tag/v0.7.0) for details of changes.
