### ISSUE TITLE
Precompiled header

### ISSUE THREAD

**Issue by vautieri** [nokotan/VSExtForEmscripten#2]
Would it be possible to support the precompiled header flag?  I don't see it as an option when copying settings from an existing project.

To add more detail:
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(395,5): error MSB4096: The item "......" in item list "ClCompile" does not define a value for metadata "PrecompiledHeaderFile".  In order to use this metadata, either qualify it by specifying %(ClCompile.PrecompiledHeaderFile), or ensure that all items in this list define a value for this metadata.

which is coming from Microsoft.CppCommon.targets

      
      <_PCHForceSyncWrite Condition="'%(ClCompile.PrecompiledHeader)' == 'NotUsing' or '%(ClCompile.PrecompiledHeader)' == ''">true</_PCHForceSyncWrite>
    </PropertyGroup>

**Comment by nokotan** [comment]
"Microsoft.Cpp.Clang.targets" has the good implementation for this, I had just pasted some corresponding parts into "Toolset.targets".
After installing [v0.4.1](https://github.com/nokotan/VSExtForEmscripten/releases/tag/v0.4.1), "Precompiled Headers" pages will appear and you will be able to use precompiled headers, please try in your develop environment.

**Comment by FrankHeimes** [comment]
`_PCHForceSyncWrite` has no effect in Visual Studio 2022, Version 17.2.2. It does not work around the problem that some compiler instances get no access to several `*.pch` files in the solution as soon as property `UseMultiToolTask` is set to `true`. So the latter - and with it the associated properties `EnforceProcessCountAcrossBuilds` and `MultiProcMaxCount` are entirely useless.
