### ISSUE TITLE
The new Update break a linking with static library

### ISSUE THREAD

**Issue by aharondavid** [nokotan/VSExtForEmscripten#25]
if you try to link to static library, you will get an compilation error.
I think that the problem is using in the wrong linking key - **l** instead of **L**

**Comment by nokotan** [comment]
Not reproducible.
Please refer the sample <https://github.com/nokotan/VSExtForEmscripten/tree/master/Test/SampleProjects/StaticLinking>.

**Comment by aharondavid** [comment]
according your sample, I had found the problem - I used in the extension **.a** what was good in the former version but not in the latest. 
I just removed the extension and add the prefix **lib** (**lib$(ProjectName)**) to the Target Name.

Thanks a lot !
