### ISSUE TITLE
Debug breakpoints are disabled

### ISSUE THREAD

**Issue by aharondavid** [nokotan/VSExtForEmscripten#26]
Hi,
Still debugger doesn't attached - break point disabled: https://github.com/nokotan/VSExtForEmscripten/issues/9

* I noticed that the Chrome is lunched with Web Assembly flag turned off.
* Debugging throughout Chrome DevTools is work to me.
* Is there any additional flags that I should Turn On ?

**Comment by nokotan** [comment]
Chrome that launched from a desktop shortcut, and that launched from WebAssembly Debugger, have different browsing profiles. Therefore, WebAssembly flag should be configured to enabled in Chrome launched from WebAssembly Debugger.

**Comment by aharondavid** [comment]
can you tell how to turn on WebAssembly flag when it launched from WebAssembly Debugger ?
what is the recommended browser for WebAssembly Debugger ?

**Comment by aharondavid** [comment]
Which browser are you using?

**Comment by nokotan** [comment]
I'm using latest chrome:

* Google Chrome Canary 109
* Google Chrome 106

This debugger may not be used with older chrome, due to incompatibility of debug adapter protocol, as same as node.js v14.

**Comment by aharondavid** [comment]
I am also use latest chrome - 106.
but how you lunched it with the WebAssembly flag enabled from the WebAssembly Debugger ?
