### ISSUE TITLE
Extra backslash in incliude paths dirs VS2022

### ISSUE THREAD

**Issue by sasmaster** [nokotan/VSExtForEmscripten#27]
Example:
This path $(EmscriptenDir)\system\include\libcxx
results in:
\upstream\emscripten\\system\include\libcxx

same is true for the rest and VS cannot detect includes in the project because of that.

**Comment by nokotan** [comment]
Have you finished to [register emscripten installation path](https://github.com/nokotan/VSExtForEmscripten#first-step-with-this-tool)?
This extension does not include emscripten nor emsdk. Please install emscripten if not.
