### ISSUE TITLE
Unable to start debugger

### ISSUE THREAD

**Issue by vb-mich** [nokotan/VSExtForEmscripten#3]
![image](https://user-images.githubusercontent.com/1304034/136317852-ddc363ce-b657-4477-9d7e-c9389938f7a7.png)

On Visual Studio 2019 Version 16.10.1
With out of the box options the WebAssembly debugger gives that error.
I tried to run VS as Administrator but it doesn't solve the issue.

**Comment by nokotan** [comment]
WebAssembly Debugger is in [the separated package](https://marketplace.visualstudio.com/items?itemName=KamenokoSoft.emscripten-debugger), so please install it additionally.

I want to set dependency with Emscripten Build Support, but it is under my investigation.

**Comment by vb-mich** [comment]
Thanks, I'd suggest to put the link into the readme.

![image](https://user-images.githubusercontent.com/1304034/136364040-4c6963a0-91fd-4a13-bc37-090fe4379d9a.png)

Anyway I'm still getting an error using the Hello World, don't really know why. It's a pity
"Failed to launch debug adapter"
"Impossible to find the specified file"

**Comment by nokotan** [comment]
Seems that Visual Studio cannot find debug adapter executable. (WebAssembly Debugger uses node.js bundled in emsdk)

I have just uploaded the extension to v0.5.4, which allows user to specify the debug adapter executable. This option is found in Project Properties -> Debuggers -> WebAssembly Debugger Page -> Debug Adapter Executable, its default value is set to %EMSDK_NODE%.

Please specify this option according to your emsdk installation.
