### ISSUE TITLE
Many FileTracker Errors

### ISSUE THREAD

**Issue by aharondavid** [nokotan/VSExtForEmscripten#30]
I get many errors about FileTracker, it is really disturb because the errors doesn't stop to spilt to the Console Build.
trying everything to stop that, doesn't help.
![image](https://user-images.githubusercontent.com/41375082/220874715-bda17c7d-5eea-4349-b490-0727169e80c7.png)

**Comment by nokotan** [comment]
Related: #24 

Please rebuild your project. These errors happen on a initial build of a emscripten project.

**Comment by aharondavid** [comment]
Hi,
It is occurs mainly when rebuild, and once the errors start splitting to the console, you can't stop it (if you try to rebuild again, it doesn't help), you should wait few minutes until it stop, and than build again
