### ISSUE TITLE
Question, is there a way to export functions?

### ISSUE THREAD

**Issue by karikera** [nokotan/VSExtForEmscripten#31]
is there a way to export functions?

**Comment by nokotan** [comment]
Use [Project Properties] > [Emscripten Linker] > [Command Line] > [Additional Options].
You can pass any flags to emscripten linker.

**Comment by karikera** [comment]
@nokotan Thanks for your answer.
I wanted to put the file instead of the command line.
and I wrote some property functions for making it.
```
-s EXPORTED_FUNCTIONS=$([System.IO.File]::ReadAllText($(ProjectDir)exports.txt).Trim().Replace("%0d%0a", ","))
```
this option will read exports.txt and concatenate lines with the comma separators.

I wish it would help someone.
