### ISSUE TITLE
Is all project property entries are relvent?

### ISSUE THREAD

**Issue by aharondavid** [nokotan/VSExtForEmscripten#7]
Is all project property entries are relvent (for example those that are pointed by the arrow in the follwing image).

![image](https://user-images.githubusercontent.com/41375082/151115142-03ca4990-e2df-4ad2-a9ee-3fdaa33e01e5.png)

**Comment by nokotan** [comment]
Most of entries in **Advanced** tab, like `Use of MFC`, `MSVC Toolset Version`, is not used with Emscripten.
